#+title: notes
#+OPTIONS: ^:nil

* User packages
** Improve

+ Start using the unstable branch
+ Integrate in Nix latests changes (.notmuch-config, mu if it has a config)
+ Stop notifs when suspended

+ Firefox auto start is very slow. Maybe launch it from nixos rather than XMonad => failed last time I tried for silly reason. Firefox launched before login
+ Not sticky at startup but remain after S-s l lock. Does not remain after natural 5mn lock

+ After M-S-l lock, luminosity remains low
+ Floating windows should always be on top. or float => see gimp export for an example
+ Increase font for qt apps like keepass

+ Bring emacs menu-bar back once it is not broken anymore (broke in NixOS 22.11) => (menu-bar-mode -1)
+ musnix (pour setup memlock) 
+ devshells
+ Dunst message about memlock not set (for wine vst plugins)

** Next

Good enough (dealt with elisp) => dunst 20mn message
Good enough => p10k config is impure
Good enough => Put everything in home.nix => firefox/opera, telegram, keepass, qBit, nemo, vlc  
