{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  mycfg = config.lab.qbittorrent;
  labcfg = config.lab;
in
  {
	options.lab.qbittorrent = {
      enable = mkEnableOption "Enable support for qBittorrent";
	};

	config = mkIf (labcfg.enable && mycfg.enable) {
    services.qbittorrent = {
      enable = true;
      openFirewall = true;

      serverConfig = {
        LegalNotice.Accepted = true;
        # Preferences = {
        #   WebUI = {
        # 	Username = "user";
        # 	Password_PBKDF2 = "generated ByteArray.";
        #   };
        General.Locale = "en";
      };

      # webuiPort = 8080;

      # package = pkgs.qbittorrent-nox; # defaults to nox

      # profileDir = "/var/lib/qbittorrent";
      # user = "qbittorrent";
      # group = "qbittorrent";
    };
  };
}
